---
- name: backup databases
  hosts: bg

  vars_files:
    - /home/dave/Documents/admin/ansible/secret.yaml

  tasks:
  - name: call backup role
    with_items: "{{ databases }}"
    ansible.builtin.include_role:
      name: backup_db
    vars:
      db: "{{ item }}"