---
- name: dump database
  community.mysql.mysql_db:
    name: "{{ db.db_name }}"
    state: dump
    target: "{{ dump_file_path }}"
    single_transaction: true
    dump_extra_args: --no-tablespaces
    quick: true
    login_password: "{{ db.db_password }}"

- name: compress dump file
  community.general.archive:
    path: "{{ dump_file_path }}"
    format: "bz2"
    remove: true

- name: fetch compressed dump file
  ansible.builtin.fetch:
    src: "{{ dump_file_path }}.bz2"
    dest: "{{ db.backup_dest | ansible.builtin.expanduser }}"
    flat: true

- name: delete dump file from server
  ansible.builtin.file:
    path: "{{ dump_file_path }}.bz2"
    state: absent
