---
ansible_ssh_user: brassgog
ansible_port: 5622
backup_dest: "/home/dave/Documents/Backups/brassgoggles.net/"
databases:
  - db_name: brassgog_forum
    backup_dir: /backups/forum
    db_password: "{{ brassgog_password }}"
  - db_name: brassgog_wiki
    backup_dir: /backups/wiki
    db_password: "{{ brassgog_password }}"
